name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
      - run: npm run ng -- add angular-cli-ghpages --skip-confirmation
      - run: npm run build
      - name: Deploy Website to gh-pages branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
        run: npm run ng -- deploy --base-href=/demo-linked-signal/ --name="$GH_NAME" --email="$GH_EMAIL"
